version: '3.7'

services:
  webserver:
    build: 
      context: .
      target: development
    container_name: 'doodah-webserver'
    expose:
      - '9000'
    ports:
        - '80:80'
    volumes:
      - ${DOCUMENT_ROOT-./app}:/var/www/app
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mongodb:
      image: mongo:bionic
      container_name: 'doodah-mongo'
      volumes:
          - mongodb:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
  vue-builder:
    build:
      context: .
      target: vue-setup
    container_name: 'doodah-vue-builder'
    volumes:
      - ./vue:/app
      - ./app/public/:/app/dist/

volumes:
    mongodb: