version: '3.7'

services:
  webserver:
    build: 
      context: .
      target: development
    container_name: 'doodah-webserver'

    volumes: 
      - ${DOCUMENT_ROOT-./app}:/var/www/app
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  vue-builder:
    build:
      context: .
      target: vue-setup
    container_name: 'doodah-vue-builder'
    volumes:
      - ./vue:/app
      - ./public/:/app/dist/
    command: rm -r /app/dist/* && yarn build
