version: '3.7'

services:
  webserver:
    build: 
      context: .
      target: development
    container_name: 'doodah-webserver'
    ports:
        - '80:80'
    volumes: 
      - ${DOCUMENT_ROOT-./app}:/var/www/app
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  vue-builder:
    build:
      context: .
      target: vue-setup
    container_name: 'doodah-vue-builder'
    volumes:
      - ./vue:/app
      - ./app/public/:/app/dist/
    command: yarn build
